name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: ricardosoaresl
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate contribution grid snake"
          add: "dist/github-contribution-grid-snake.svg"
